// Fetch User 
export const FETCH_USER_PENDING = "FETCH_USER_PENDING"
export const FETCH_USER_SUCCEED = "FETCH_USER_SUCCEED"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"

// Fetch Message
export const FETCH_MESSAGE_PENDING = "FETCH_MESSAGE_PENDING"
export const FETCH_MESSAGE_SUCCEED = "FETCH_MESSAGE_SUCCEED"
export const FETCH_MESSAGE_FAILED = "FETCH_MESSAGE_FAILED"

// Fetch Message
export const MESSAGE_UPDATE = "MESSAGE_UPDATE"
export const MESSAGE_UPDATE_SUCCEED = "MESSAGE_UPDATE_SUCCEED"
export const MESSAGE_UPDATE_FAILED = "MESSAGE_UPDATE_FAILED"

// Message Clean Up
export const MESSAGE_CLEAN_UP = "MESSAGE_CLEAN_UP"